default_platform(:ios)

platform :ios do
  desc "Create app on Apple Developer and App Store Connect sites"
  lane :create_app do
​    produce
   end

desc "Take screenshots"
  lane :screenshot do
    snapshot
  end
  
desc "Create ipa"
  lane :build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end
  
desc "Upload to App Store"
  lane :upload do
    deliver
  end

  
end
