# 1 - A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
    "iPhone 8 Plus"
])

# 2 - A list of supported languages

languages([
  'pt-BR',
])

# 3 - The name of the scheme which contains the UI Tests

scheme("Loterias-Da-Sorte-iOSUITests")

# 4 - Where should the resulting screenshots be stored?

output_directory "./fastlane/screenshots"

# 5 - Clears previous screenshots

clear_previous_screenshots(true)
